// Skin pixel data consumed by the software board renderer (board_layer). Generated by tools/gen_art.py
// into skin_data.cpp. All pixel arrays are 8bpp palette indices into the skin's board palette;
// index 0 = transparent for stones/markers (the board texture itself never uses 0).
#pragma once
#include <cstdint>

namespace skins {

enum class Skin : uint8_t { CLASSIC = 0, PUP = 1, DINO = 2 };
constexpr int SKIN_COUNT = 3;

struct Sprite8 { uint8_t w, h; const uint8_t* px; };   // row-major, w*h indices

struct StoneSet {                 // one per cell size
    uint8_t cell;                 // 16, 11 or 8 (sprites are cell x cell)
    Sprite8 black, white;         // normal stones
    Sprite8 black_atari, white_atari;   // atari flash variant (lighter / outlined)
    Sprite8 ghost_black, ghost_white;   // placement preview (dithered / outline)
    Sprite8 last_marker;          // drawn over the last-played stone (contrasting dot/square)
    Sprite8 dead_marker;          // X over a dead stone (marking phase)
    Sprite8 terr_black, terr_white;     // territory marks for the estimate view (small squares)
    Sprite8 mission_marker;       // ring/triangle marking objective points on empty or stone
};

struct SkinData {
    const uint16_t* palette;      // BGR555 colours (bit 15 = 0). Entry 0 unused (transparent).
    uint16_t palette_size;        // <= 64
    uint8_t bg_index;             // flat board background colour
    uint8_t line_index;           // grid line colour
    uint8_t hoshi_index;          // star-point colour
    uint8_t margin_index;         // colour outside the grid (board margin)
    Sprite8 board_texture;        // 32x32 tileable texture drawn under the grid (wood / lawn / slab)
    Sprite8 margin_texture;       // 16x16 tileable margin decoration (w = 0 if none): DINO footprints, PUP grass
    StoneSet stones[3];           // [0] 16 px (7x7 & 9x9), [1] 11 px (13x13), [2] 8 px (19x19)
};

const SkinData& skin(Skin s);

}  // namespace skins
