// 3x3 pattern table (hand-authored, ~40 patterns, all 8 symmetries + colour swap expanded into a
// 65536-entry lookup table indexed by the 8 neighbours of a point, 2 bits each).
//
// Neighbour encoding, clockwise from top-left: NW N NE E SE S SW W, each 2 bits:
// 0 = empty, 1 = to-move colour (own), 2 = opponent, 3 = off board. index = sum(code_i << (2*i)).
// Value = weight 0..255 for the side to move playing at the centre (0 = no pattern / discouraged).
#pragma once
#include "go/board.h"

namespace ai {

constexpr int PATTERN_TABLE_SIZE = 65536;
extern const uint8_t PATTERN_TABLE[PATTERN_TABLE_SIZE];   // generated by tools/gen_patterns.py into patterns_table.cpp

// Computes the 16-bit neighbourhood key of point p for colour c (p empty, on board).
uint16_t pattern_key(const go::Board& b, go::Point p, go::Color c);
inline uint8_t pattern_weight(const go::Board& b, go::Point p, go::Color c) { return PATTERN_TABLE[pattern_key(b, p, c)]; }

}  // namespace ai
