/*
 * MOKU - Tactics of Go: font metrics, without Butano.
 * Generated by tools/gen_font.py - do not edit by hand, edit the generator.
 *
 * moku_fonts.h builds the bn::sprite_font objects from these same tables, so a width measured
 * here is the width the GBA draws. The host tests use it to prove that every string fits the box
 * it is drawn in, in pixels rather than in characters.
 */

#ifndef MOKU_FONT_WIDTHS_H
#define MOKU_FONT_WIDTHS_H

#include <cstdint>

namespace fonts
{

// ASCII 32..126 in order, then these UTF-8 glyphs, in this order.
constexpr const char* moku_font_utf8_strings[] = {
    "À", "Â", "Ç", "É", "È", "Ê", "Ë", "Î", "Ï", "Ô", "Ù", "Û", "Ü", "Œ",
    "à", "â", "ç", "é", "è", "ê", "ë", "î", "ï", "ô", "ù", "û", "ü", "œ",
    "’", "«", "»", "…", "·", "★", "☆", "▲", "▼", "▶", "◀", "×", "←", "↑",
    "→", "↓", "▮", "▯", "©"
};

constexpr int moku_font_utf8_count = int(sizeof(moku_font_utf8_strings) / sizeof(moku_font_utf8_strings[0]));

constexpr int8_t moku_font_8_widths[] = {
    3,  // 32 space
    2,  // 33 !
    4,  // 34 "
    6,  // 35 #
    6,  // 36 $
    6,  // 37 %
    6,  // 38 &
    2,  // 39 '
    3,  // 40 (
    3,  // 41 )
    6,  // 42 *
    6,  // 43 +
    3,  // 44 ,
    4,  // 45 -
    2,  // 46 .
    4,  // 47 /
    6,  // 48 0
    6,  // 49 1
    6,  // 50 2
    6,  // 51 3
    6,  // 52 4
    6,  // 53 5
    6,  // 54 6
    6,  // 55 7
    6,  // 56 8
    6,  // 57 9
    2,  // 58 :
    3,  // 59 ;
    4,  // 60 <
    5,  // 61 =
    4,  // 62 >
    6,  // 63 ?
    6,  // 64 @
    6,  // 65 A
    6,  // 66 B
    6,  // 67 C
    6,  // 68 D
    6,  // 69 E
    6,  // 70 F
    6,  // 71 G
    6,  // 72 H
    4,  // 73 I
    5,  // 74 J
    6,  // 75 K
    6,  // 76 L
    6,  // 77 M
    6,  // 78 N
    6,  // 79 O
    6,  // 80 P
    6,  // 81 Q
    6,  // 82 R
    6,  // 83 S
    6,  // 84 T
    6,  // 85 U
    6,  // 86 V
    6,  // 87 W
    6,  // 88 X
    6,  // 89 Y
    6,  // 90 Z
    3,  // 91 [
    4,  // 92 backslash
    3,  // 93 ]
    4,  // 94 ^
    6,  // 95 _
    3,  // 96 `
    5,  // 97 a
    5,  // 98 b
    5,  // 99 c
    5,  // 100 d
    5,  // 101 e
    4,  // 102 f
    5,  // 103 g
    5,  // 104 h
    2,  // 105 i
    3,  // 106 j
    5,  // 107 k
    3,  // 108 l
    6,  // 109 m
    5,  // 110 n
    5,  // 111 o
    5,  // 112 p
    5,  // 113 q
    4,  // 114 r
    5,  // 115 s
    4,  // 116 t
    5,  // 117 u
    4,  // 118 v
    6,  // 119 w
    4,  // 120 x
    5,  // 121 y
    5,  // 122 z
    4,  // 123 {
    2,  // 124 |
    4,  // 125 }
    6,  // 126 ~
    6,  // U+00C0 À
    6,  // U+00C2 Â
    6,  // U+00C7 Ç
    6,  // U+00C9 É
    6,  // U+00C8 È
    6,  // U+00CA Ê
    6,  // U+00CB Ë
    4,  // U+00CE Î
    4,  // U+00CF Ï
    6,  // U+00D4 Ô
    6,  // U+00D9 Ù
    6,  // U+00DB Û
    6,  // U+00DC Ü
    8,  // U+0152 Œ
    5,  // U+00E0 à
    5,  // U+00E2 â
    5,  // U+00E7 ç
    5,  // U+00E9 é
    5,  // U+00E8 è
    5,  // U+00EA ê
    5,  // U+00EB ë
    4,  // U+00EE î
    4,  // U+00EF ï
    5,  // U+00F4 ô
    5,  // U+00F9 ù
    5,  // U+00FB û
    5,  // U+00FC ü
    8,  // U+0153 œ
    3,  // U+2019 ’
    5,  // U+00AB «
    5,  // U+00BB »
    6,  // U+2026 …
    2,  // U+00B7 ·
    8,  // U+2605 ★
    8,  // U+2606 ☆
    6,  // U+25B2 ▲
    6,  // U+25BC ▼
    5,  // U+25B6 ▶
    5,  // U+25C0 ◀
    4,  // U+00D7 ×
    6,  // U+2190 ←
    6,  // U+2191 ↑
    6,  // U+2192 →
    6,  // U+2193 ↓
    4,  // U+25AE ▮
    4,  // U+25AF ▯
    8,  // U+00A9 ©
};

constexpr int8_t moku_font_16_widths[] = {
    4,  // 32 space
    3,  // 33 !
    6,  // 34 "
    8,  // 35 #
    8,  // 36 $
    8,  // 37 %
    8,  // 38 &
    3,  // 39 '
    4,  // 40 (
    4,  // 41 )
    8,  // 42 *
    7,  // 43 +
    3,  // 44 ,
    6,  // 45 -
    3,  // 46 .
    8,  // 47 /
    8,  // 48 0
    8,  // 49 1
    8,  // 50 2
    8,  // 51 3
    8,  // 52 4
    8,  // 53 5
    8,  // 54 6
    8,  // 55 7
    8,  // 56 8
    8,  // 57 9
    3,  // 58 :
    4,  // 59 ;
    6,  // 60 <
    7,  // 61 =
    6,  // 62 >
    8,  // 63 ?
    8,  // 64 @
    8,  // 65 A
    8,  // 66 B
    8,  // 67 C
    8,  // 68 D
    8,  // 69 E
    8,  // 70 F
    8,  // 71 G
    8,  // 72 H
    5,  // 73 I
    7,  // 74 J
    8,  // 75 K
    8,  // 76 L
    8,  // 77 M
    8,  // 78 N
    8,  // 79 O
    8,  // 80 P
    8,  // 81 Q
    8,  // 82 R
    8,  // 83 S
    8,  // 84 T
    8,  // 85 U
    8,  // 86 V
    8,  // 87 W
    8,  // 88 X
    8,  // 89 Y
    8,  // 90 Z
    4,  // 91 [
    8,  // 92 backslash
    4,  // 93 ]
    6,  // 94 ^
    8,  // 95 _
    4,  // 96 `
    8,  // 97 a
    8,  // 98 b
    8,  // 99 c
    8,  // 100 d
    8,  // 101 e
    8,  // 102 f
    8,  // 103 g
    8,  // 104 h
    5,  // 105 i
    7,  // 106 j
    8,  // 107 k
    8,  // 108 l
    8,  // 109 m
    8,  // 110 n
    8,  // 111 o
    8,  // 112 p
    8,  // 113 q
    8,  // 114 r
    8,  // 115 s
    8,  // 116 t
    8,  // 117 u
    8,  // 118 v
    8,  // 119 w
    8,  // 120 x
    8,  // 121 y
    8,  // 122 z
    5,  // 123 {
    3,  // 124 |
    5,  // 125 }
    8,  // 126 ~
    8,  // U+00C0 À
    8,  // U+00C2 Â
    8,  // U+00C7 Ç
    8,  // U+00C9 É
    8,  // U+00C8 È
    8,  // U+00CA Ê
    8,  // U+00CB Ë
    5,  // U+00CE Î
    5,  // U+00CF Ï
    8,  // U+00D4 Ô
    8,  // U+00D9 Ù
    8,  // U+00DB Û
    8,  // U+00DC Ü
    8,  // U+0152 Œ
    8,  // U+00E0 à
    8,  // U+00E2 â
    8,  // U+00E7 ç
    8,  // U+00E9 é
    8,  // U+00E8 è
    8,  // U+00EA ê
    8,  // U+00EB ë
    5,  // U+00EE î
    5,  // U+00EF ï
    8,  // U+00F4 ô
    8,  // U+00F9 ù
    8,  // U+00FB û
    8,  // U+00FC ü
    8,  // U+0153 œ
    3,  // U+2019 ’
    8,  // U+00AB «
    8,  // U+00BB »
    8,  // U+2026 …
    3,  // U+00B7 ·
    8,  // U+2605 ★
    8,  // U+2606 ☆
    8,  // U+25B2 ▲
    8,  // U+25BC ▼
    6,  // U+25B6 ▶
    6,  // U+25C0 ◀
    7,  // U+00D7 ×
    8,  // U+2190 ←
    8,  // U+2191 ↑
    8,  // U+2192 →
    8,  // U+2193 ↓
    6,  // U+25AE ▮
    6,  // U+25AF ▯
    8,  // U+00A9 ©
};

// Width in pixels of a UTF-8 string, by the same metric bn::sprite_text_generator uses:
// the sum of the character widths, no extra spacing. Control characters count as 0; an unknown
// UTF-8 character counts as 0 and sets `unknown`.
[[nodiscard]] constexpr int moku_text_width(const char* text, const int8_t* widths, bool* unknown = nullptr)
{
    int width = 0;

    while(*text)
    {
        const unsigned char c = static_cast<unsigned char>(*text);

        if(c < 128)
        {
            if(c == 32)
            {
                width += widths[0];
            }
            else if(c > 32 && c < 127)
            {
                width += widths[c - 32];
            }

            ++text;
            continue;
        }

        int length = 1;

        if((c & 0xE0) == 0xC0)      length = 2;
        else if((c & 0xF0) == 0xE0) length = 3;
        else if((c & 0xF8) == 0xF0) length = 4;

        int found = -1;

        for(int i = 0; i < moku_font_utf8_count; ++i)
        {
            const char* candidate = moku_font_utf8_strings[i];
            int j = 0;

            while(j < length && candidate[j] && candidate[j] == text[j])
            {
                ++j;
            }

            if(j == length && candidate[j] == 0)
            {
                found = i;
                break;
            }
        }

        if(found >= 0)
        {
            width += widths[95 + found];
        }
        else if(unknown)
        {
            *unknown = true;
        }

        text += length;
    }

    return width;
}

}

#endif
