/*
 * MOKU - Tactics of Go: pixel fonts.
 * Generated by tools/gen_font.py - do not edit by hand, edit the generator.
 *
 * font_8  : 8x8 cell, variable width. Caps 6 px tall, x-height 4, 1 px descender.
 * font_16 : 8x16 cell, variable width, bold caps-only display face (lowercase
 *           folds to the capital glyphs).
 * Both fonts accept the same character set: ASCII 32..126 plus the UTF-8
 * glyphs listed in moku_font_utf8_characters. Ink is palette index 1 only.
 */

#ifndef MOKU_FONTS_H
#define MOKU_FONTS_H

#include "bn_sprite_font.h"
#include "bn_utf8_characters_map.h"
#include "bn_sprite_items_font_8.h"
#include "bn_sprite_items_font_16.h"

// The width tables themselves, with no Butano in them, so host tests measure the same pixels.
#include "moku_font_widths.h"

namespace fonts
{

constexpr bn::utf8_character moku_font_utf8_characters[] = {
    "À", "Â", "Ç", "É", "È", "Ê", "Ë", "Î", "Ï", "Ô", "Ù", "Û", "Ü", "Œ",
    "à", "â", "ç", "é", "è", "ê", "ë", "î", "ï", "ô", "ù", "û", "ü", "œ",
    "’", "«", "»", "…", "·", "★", "☆", "▲", "▼", "▶", "◀", "×", "←", "↑",
    "→", "↓", "▮", "▯", "©"
};

constexpr bn::span<const int8_t> moku_font_8_character_widths(moku_font_8_widths);

constexpr bn::span<const int8_t> moku_font_16_character_widths(moku_font_16_widths);

constexpr bn::span<const bn::utf8_character> moku_font_utf8_characters_span(moku_font_utf8_characters);

constexpr auto moku_font_utf8_characters_map = bn::utf8_characters_map<moku_font_utf8_characters_span>();

constexpr bn::sprite_font moku_font_8(
        bn::sprite_items::font_8, moku_font_utf8_characters_map.reference(), moku_font_8_character_widths);

constexpr bn::sprite_font moku_font_16(
        bn::sprite_items::font_16, moku_font_utf8_characters_map.reference(), moku_font_16_character_widths);

constexpr int moku_font_8_height = 8;    //!< Cell height; use 8 for tight lines, 10 for dialogue.
constexpr int moku_font_8_baseline = 7;  //!< Rows above the descender row (baseline is row 6, descender row 7).
constexpr int moku_font_8_space_width = 3;
constexpr int moku_font_16_height = 16;
constexpr int moku_font_16_baseline = 15;  //!< Letters sit on row 14; row 15 holds cedillas / commas.
constexpr int moku_font_16_space_width = 4;

/**
 * @brief Width in pixels of a UTF-8 text rendered with the given MOKU font
 * (same metric bn::sprite_text_generator uses: character widths, no extra spacing).
 * ASCII control characters count as 0 pixels; an unknown UTF-8 character is an error.
 */
[[nodiscard]] constexpr int text_width(const bn::sprite_font& font, const char* text)
{
    const bn::span<const int8_t>& widths = font.character_widths_ref();
    const bn::utf8_characters_map_ref& utf8_map = font.utf8_characters_ref();
    int width = 0;

    while(*text)
    {
        unsigned char c = static_cast<unsigned char>(*text);

        if(c == ' ')
        {
            width += widths[0];
            ++text;
        }
        else if(c < 128)
        {
            if(c > 32 && c < 127)
            {
                width += widths[c - 32];
            }

            ++text;
        }
        else
        {
            bn::utf8_character utf8_char(*text);
            width += widths[95 + utf8_map.index(utf8_char)];
            text += utf8_char.size();
        }
    }

    return width;
}

}

#endif
