#!/usr/bin/env python3
"""Regenerate tests/rom/scripts/12_missions.txt from the mission table that ships in the ROM.

The mission ROM test plays each mission's scripted solution through TCMD_PLAY_POINT. Reading the
solutions straight out of src/game/missions_data.cpp means the test can never drift from the game:
change a position in tools/gen_missions.py, regenerate, and the ROM test follows.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from goref import BLACK, WHITE, EMPTY, Board, CAPTURED, read_ladder

WHOLE_GAMES = {15, 19, 20}
LADDER_MISSIONS = {6}


def engine_line(root, mission_id):
    """Asks the engine itself for the moves that solve a mission.

    The ladder cannot be scripted from a static table: which side to atari from depends on the
    position after each of the opponent's forced answers, so the line comes from tests/host/
    tool_mission_line, built from the same sources as the ROM.
    """
    import subprocess

    for candidate in ("build-host/tool_mission_line", "../build-host/tool_mission_line"):
        path = os.path.join(root, candidate)
        if os.path.exists(path):
            out = subprocess.run([path, str(mission_id)], capture_output=True, text=True)
            if out.returncode != 0:
                raise SystemExit("tool_mission_line could not solve mission %d:\n%s" % (mission_id, out.stderr))
            moves = []
            for line in out.stdout.split("\n"):
                line = line.strip()
                if line == "pass":
                    moves.append(None)
                elif line:
                    x, y = line.split()
                    moves.append((int(x), int(y)))
            return moves

    raise SystemExit("build-host/tool_mission_line is missing: build the host tests first")


def mission_setup(root, prefix):
    """Reads a mission's board size, setup stones and marked points out of missions_data.cpp."""
    src = open(os.path.join(root, "src", "game", "missions_data.cpp")).read()
    stones = []
    m = re.search(r"const SetupStone %s_STONES\[\] = \{ (.*?) \};" % prefix, src)
    if m:
        for x, y, colour in re.findall(r"\{(\d+), (\d+), go::(BLACK|WHITE)\}", m.group(1)):
            stones.append((int(x), int(y), BLACK if colour == "BLACK" else WHITE))
    marked = []
    m = re.search(r"const XY %s_MARKED\[\] = \{ (.*?) \};" % prefix, src)
    if m:
        marked = [(int(a), int(b)) for a, b in re.findall(r"\{(-?\d+), (-?\d+)\}", m.group(1))]
    size = 9
    m = re.search(r"\.id = %d,\s*\.board = (\d+)" % int(prefix[1:]), src)
    if m:
        size = int(m.group(1))
    return {"size": size, "stones": stones, "marked": marked}


def solutions(root):
    src = open(os.path.join(root, "src", "game", "missions_data.cpp")).read()
    out = {}
    for m in re.finditer(r"const XY (M\d\d|T18_\d)_SOLUTION\[\] = \{ (.*?) \};", src):
        out[m.group(1)] = [(int(a), int(b)) for a, b in re.findall(r"\{(-?\d+), (-?\d+)\}", m.group(2))]
    return out


def play(x, y):
    return ["write32 $g_moku_test+76 %d" % ((y << 8) | x), "write32 $g_moku_test+72 16",
            "wait32 $g_moku_test+72 0 60", "frames 40"]


def settle():
    """A command may switch scenes; the new scene publishes its state on its first update."""
    return ["frames 6"]


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sol = solutions(root)
    lines = [
        "# Generated by tools/gen_rom_tests.py - every campaign mission, loaded and solved with the",
        "# scripted solution that ships in the ROM, then the mission status must say CLEAR.",
        "symbols build/moku.sym",
        "wait8 $g_moku_test+8 1 120",
        "frames 20",
        "write32 $g_moku_test+72 8",
        "wait32 $g_moku_test+72 0 20",
        "frames 6",
        "",
    ]

    for i in range(1, 21):
        lines += ["echo mission %d" % i,
                  "write32 $g_moku_test+76 %d" % i,
                  "write32 $g_moku_test+72 2",
                  "wait32 $g_moku_test+72 0 40", "frames 6",
                  "assert8 $g_moku_test+26 %d" % i,
                  "write32 $g_moku_test+72 12",
                  "wait32 $g_moku_test+72 0 20", "frames 6"]

        if i in WHOLE_GAMES:
            lines += ["# a whole game: the host suite plays these out, here we only check the setup",
                      "assert8 $g_moku_test+27 0", "screenshot tests/rom/out/12_mission_%02d.png" % i, ""]
            continue

        if i == 18:
            for stage in range(1, 6):
                for x, y in sol.get("T18_%d" % stage, []):
                    lines += play(x, y) + ["frames 30"]
            lines += ["frames 60", "assert8 $g_moku_test+27 1",
                      "screenshot tests/rom/out/12_mission_18.png", ""]
            continue

        moves = engine_line(root, i) if i in LADDER_MISSIONS else \
            [(x, y) if x >= 0 else None for x, y in sol.get("M%02d" % i, [])]

        if i in LADDER_MISSIONS:
            lines.append("# the ladder, read out by the engine itself (tool_mission_line)")

        for move in moves:
            if move is None:
                lines += ["write32 $g_moku_test+72 17", "wait32 $g_moku_test+72 0 60", "frames 40"]
            else:
                lines += play(move[0], move[1])



        lines += ["frames 90", "assert8 $g_moku_test+27 1",
                  "screenshot tests/rom/out/12_mission_%02d.png" % i, ""]

    lines += ["# The rule is about the human's turn: no missed frame while the player has the",
              "# move. Scene loads and the AI's own turn on a big board may cost a few; they are read",
              "# out rather than asserted.",
              "wait8 $g_moku_test+30 0 900",
              "write32 $g_moku_test+72 9", "wait32 $g_moku_test+72 0 20", "frames 6", "frames 150",
              "assert16 $g_moku_test+38 0", "read32 $g_moku_test+84", "stats"]
    path = os.path.join(root, "tests", "rom", "scripts", "12_missions.txt")
    open(path, "w").write("\n".join(lines) + "\n")
    print("wrote %s (%d lines)" % (path, len(lines)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
